# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/ZYBO_Master.xdc

# Block Designs: bd/zybo_hdmi_in/zybo_hdmi_in.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in || ORIG_REF_NAME==zybo_hdmi_in}]

# IP: bd/zybo_hdmi_in/ip/zybo_hdmi_in_axi_dynclk_0_0/zybo_hdmi_in_axi_dynclk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_axi_dynclk_0_0 || ORIG_REF_NAME==zybo_hdmi_in_axi_dynclk_0_0}]

# IP: bd/zybo_hdmi_in/ip/zybo_hdmi_in_axi_gpio_video_0/zybo_hdmi_in_axi_gpio_video_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_axi_gpio_video_0 || ORIG_REF_NAME==zybo_hdmi_in_axi_gpio_video_0}]

# IP: bd/zybo_hdmi_in/ip/zybo_hdmi_in_axi_mem_intercon_0/zybo_hdmi_in_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_axi_mem_intercon_0 || ORIG_REF_NAME==zybo_hdmi_in_axi_mem_intercon_0}]

# IP: bd/zybo_hdmi_in/ip/zybo_hdmi_in_xbar_0/zybo_hdmi_in_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_xbar_0 || ORIG_REF_NAME==zybo_hdmi_in_xbar_0}]

# IP: bd/zybo_hdmi_in/ip/zybo_hdmi_in_axi_vdma_0_0/zybo_hdmi_in_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_axi_vdma_0_0 || ORIG_REF_NAME==zybo_hdmi_in_axi_vdma_0_0}]

# IP: bd/zybo_hdmi_in/ip/zybo_hdmi_in_dvi2rgb_0_0/zybo_hdmi_in_dvi2rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_dvi2rgb_0_0 || ORIG_REF_NAME==zybo_hdmi_in_dvi2rgb_0_0}]

# IP: bd/zybo_hdmi_in/ip/zybo_hdmi_in_proc_sys_reset_0_0/zybo_hdmi_in_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_proc_sys_reset_0_0 || ORIG_REF_NAME==zybo_hdmi_in_proc_sys_reset_0_0}]

# IP: bd/zybo_hdmi_in/ip/zybo_hdmi_in_proc_sys_reset_1_0/zybo_hdmi_in_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_proc_sys_reset_1_0 || ORIG_REF_NAME==zybo_hdmi_in_proc_sys_reset_1_0}]

# IP: bd/zybo_hdmi_in/ip/zybo_hdmi_in_proc_sys_reset_3_0/zybo_hdmi_in_proc_sys_reset_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_proc_sys_reset_3_0 || ORIG_REF_NAME==zybo_hdmi_in_proc_sys_reset_3_0}]

# IP: bd/zybo_hdmi_in/ip/zybo_hdmi_in_proc_sys_reset_hdmi_in_0/zybo_hdmi_in_proc_sys_reset_hdmi_in_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_proc_sys_reset_hdmi_in_0 || ORIG_REF_NAME==zybo_hdmi_in_proc_sys_reset_hdmi_in_0}]

# IP: bd/zybo_hdmi_in/ip/zybo_hdmi_in_processing_system7_0_0/zybo_hdmi_in_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_processing_system7_0_0 || ORIG_REF_NAME==zybo_hdmi_in_processing_system7_0_0}]

# IP: bd/zybo_hdmi_in/ip/zybo_hdmi_in_processing_system7_0_axi_periph_0/zybo_hdmi_in_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==zybo_hdmi_in_processing_system7_0_axi_periph_0}]

# IP: bd/zybo_hdmi_in/ip/zybo_hdmi_in_xbar_1/zybo_hdmi_in_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_xbar_1 || ORIG_REF_NAME==zybo_hdmi_in_xbar_1}]

# IP: bd/zybo_hdmi_in/ip/zybo_hdmi_in_v_axi4s_vid_out_0_0/zybo_hdmi_in_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==zybo_hdmi_in_v_axi4s_vid_out_0_0}]

# IP: bd/zybo_hdmi_in/ip/zybo_hdmi_in_v_tc_0_0/zybo_hdmi_in_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_v_tc_0_0 || ORIG_REF_NAME==zybo_hdmi_in_v_tc_0_0}]

# IP: bd/zybo_hdmi_in/ip/zybo_hdmi_in_v_vid_in_axi4s_0_0/zybo_hdmi_in_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==zybo_hdmi_in_v_vid_in_axi4s_0_0}]

# IP: bd/zybo_hdmi_in/ip/zybo_hdmi_in_xlconcat_0_0/zybo_hdmi_in_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_xlconcat_0_0 || ORIG_REF_NAME==zybo_hdmi_in_xlconcat_0_0}]

# IP: bd/zybo_hdmi_in/ip/zybo_hdmi_in_xlconstant_0_0/zybo_hdmi_in_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_xlconstant_0_0 || ORIG_REF_NAME==zybo_hdmi_in_xlconstant_0_0}]

# IP: bd/zybo_hdmi_in/ip/zybo_hdmi_in_xlslice_0_0/zybo_hdmi_in_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_xlslice_0_0 || ORIG_REF_NAME==zybo_hdmi_in_xlslice_0_0}]

# IP: bd/zybo_hdmi_in/ip/zybo_hdmi_in_xlslice_green_0/zybo_hdmi_in_xlslice_green_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_xlslice_green_0 || ORIG_REF_NAME==zybo_hdmi_in_xlslice_green_0}]

# IP: bd/zybo_hdmi_in/ip/zybo_hdmi_in_xlslice_blue_0/zybo_hdmi_in_xlslice_blue_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_xlslice_blue_0 || ORIG_REF_NAME==zybo_hdmi_in_xlslice_blue_0}]

# IP: bd/zybo_hdmi_in/ip/zybo_hdmi_in_xlconcat_1_0/zybo_hdmi_in_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_xlconcat_1_0 || ORIG_REF_NAME==zybo_hdmi_in_xlconcat_1_0}]

# IP: bd/zybo_hdmi_in/ip/zybo_hdmi_in_rgb2vga_0_1/zybo_hdmi_in_rgb2vga_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_rgb2vga_0_1 || ORIG_REF_NAME==zybo_hdmi_in_rgb2vga_0_1}]

# IP: bd/zybo_hdmi_in/ip/zybo_hdmi_in_s00_regslice_0/zybo_hdmi_in_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_s00_regslice_0 || ORIG_REF_NAME==zybo_hdmi_in_s00_regslice_0}]

# IP: bd/zybo_hdmi_in/ip/zybo_hdmi_in_s01_regslice_0/zybo_hdmi_in_s01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_s01_regslice_0 || ORIG_REF_NAME==zybo_hdmi_in_s01_regslice_0}]

# IP: bd/zybo_hdmi_in/ip/zybo_hdmi_in_m00_regslice_0/zybo_hdmi_in_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_m00_regslice_0 || ORIG_REF_NAME==zybo_hdmi_in_m00_regslice_0}]

# IP: bd/zybo_hdmi_in/ip/zybo_hdmi_in_auto_pc_0/zybo_hdmi_in_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_auto_pc_0 || ORIG_REF_NAME==zybo_hdmi_in_auto_pc_0}]

# IP: bd/zybo_hdmi_in/ip/zybo_hdmi_in_auto_pc_1/zybo_hdmi_in_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_auto_pc_1 || ORIG_REF_NAME==zybo_hdmi_in_auto_pc_1}]

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_axi_gpio_video_0/zybo_hdmi_in_axi_gpio_video_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_axi_gpio_video_0 || ORIG_REF_NAME==zybo_hdmi_in_axi_gpio_video_0}] {/U0 }]/U0 ]]

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_axi_gpio_video_0/zybo_hdmi_in_axi_gpio_video_0_ooc.xdc

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_axi_gpio_video_0/zybo_hdmi_in_axi_gpio_video_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_axi_gpio_video_0 || ORIG_REF_NAME==zybo_hdmi_in_axi_gpio_video_0}] {/U0 }]/U0 ]]

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_xbar_0/zybo_hdmi_in_xbar_0_ooc.xdc

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_axi_vdma_0_0/zybo_hdmi_in_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_axi_vdma_0_0 || ORIG_REF_NAME==zybo_hdmi_in_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_axi_vdma_0_0/zybo_hdmi_in_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_axi_vdma_0_0 || ORIG_REF_NAME==zybo_hdmi_in_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_axi_vdma_0_0/zybo_hdmi_in_axi_vdma_0_0_ooc.xdc

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_dvi2rgb_0_0/src/dvi2rgb.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_dvi2rgb_0_0 || ORIG_REF_NAME==zybo_hdmi_in_dvi2rgb_0_0}] {/U0 }]/U0 ]]

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_dvi2rgb_0_0/src/dvi2rgb_ooc.xdc

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_proc_sys_reset_0_0/zybo_hdmi_in_proc_sys_reset_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_proc_sys_reset_0_0 || ORIG_REF_NAME==zybo_hdmi_in_proc_sys_reset_0_0}]

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_proc_sys_reset_0_0/zybo_hdmi_in_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_proc_sys_reset_0_0 || ORIG_REF_NAME==zybo_hdmi_in_proc_sys_reset_0_0}]

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_proc_sys_reset_0_0/zybo_hdmi_in_proc_sys_reset_0_0_ooc.xdc

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_proc_sys_reset_1_0/zybo_hdmi_in_proc_sys_reset_1_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_proc_sys_reset_1_0 || ORIG_REF_NAME==zybo_hdmi_in_proc_sys_reset_1_0}]

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_proc_sys_reset_1_0/zybo_hdmi_in_proc_sys_reset_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_proc_sys_reset_1_0 || ORIG_REF_NAME==zybo_hdmi_in_proc_sys_reset_1_0}]

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_proc_sys_reset_1_0/zybo_hdmi_in_proc_sys_reset_1_0_ooc.xdc

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_proc_sys_reset_3_0/zybo_hdmi_in_proc_sys_reset_3_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_proc_sys_reset_3_0 || ORIG_REF_NAME==zybo_hdmi_in_proc_sys_reset_3_0}]

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_proc_sys_reset_3_0/zybo_hdmi_in_proc_sys_reset_3_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_proc_sys_reset_3_0 || ORIG_REF_NAME==zybo_hdmi_in_proc_sys_reset_3_0}]

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_proc_sys_reset_3_0/zybo_hdmi_in_proc_sys_reset_3_0_ooc.xdc

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_proc_sys_reset_hdmi_in_0/zybo_hdmi_in_proc_sys_reset_hdmi_in_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_proc_sys_reset_hdmi_in_0 || ORIG_REF_NAME==zybo_hdmi_in_proc_sys_reset_hdmi_in_0}]

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_proc_sys_reset_hdmi_in_0/zybo_hdmi_in_proc_sys_reset_hdmi_in_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_proc_sys_reset_hdmi_in_0 || ORIG_REF_NAME==zybo_hdmi_in_proc_sys_reset_hdmi_in_0}]

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_proc_sys_reset_hdmi_in_0/zybo_hdmi_in_proc_sys_reset_hdmi_in_0_ooc.xdc

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_processing_system7_0_0/zybo_hdmi_in_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_processing_system7_0_0 || ORIG_REF_NAME==zybo_hdmi_in_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_xbar_1/zybo_hdmi_in_xbar_1_ooc.xdc

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_v_axi4s_vid_out_0_0/zybo_hdmi_in_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==zybo_hdmi_in_v_axi4s_vid_out_0_0}] {/inst }]/inst ]]

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_v_axi4s_vid_out_0_0/zybo_hdmi_in_v_axi4s_vid_out_0_0_ooc.xdc

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_v_tc_0_0/zybo_hdmi_in_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_v_tc_0_0 || ORIG_REF_NAME==zybo_hdmi_in_v_tc_0_0}] {/U0 }]/U0 ]]

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_v_tc_0_0/zybo_hdmi_in_v_tc_0_0_ooc.xdc

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_v_vid_in_axi4s_0_0/zybo_hdmi_in_v_vid_in_axi4s_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zybo_hdmi_in_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==zybo_hdmi_in_v_vid_in_axi4s_0_0}] {/inst }]/inst ]]

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_v_vid_in_axi4s_0_0/zybo_hdmi_in_v_vid_in_axi4s_0_0_ooc.xdc

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_s00_regslice_0/zybo_hdmi_in_s00_regslice_0_ooc.xdc

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_s01_regslice_0/zybo_hdmi_in_s01_regslice_0_ooc.xdc

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_m00_regslice_0/zybo_hdmi_in_m00_regslice_0_ooc.xdc

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_auto_pc_0/zybo_hdmi_in_auto_pc_0_ooc.xdc

# XDC: bd/zybo_hdmi_in/ip/zybo_hdmi_in_auto_pc_1/zybo_hdmi_in_auto_pc_1_ooc.xdc

# XDC: bd/zybo_hdmi_in/zybo_hdmi_in_ooc.xdc
